import { NextRequest } from "next/server";
import { prisma } from "@/lib/db";
import { generateStory } from "@/lib/story-generator";
import { createStoryFromMedia, pickLibraryFile } from "@/lib/story-media";
import { publishStoryRecord } from "@/lib/story-publisher";
import { getIgToken } from "@/lib/ig-token";
import { runRecurring, RECURRING_WINDOW_MS } from "@/lib/recurring";
import { learnToneProfile, TONE_REFRESH_MS } from "@/lib/tone";
import type { IgAccount } from "@/generated/prisma/client";

export const runtime = "nodejs";
export const maxDuration = 300;

// 自動投稿の実行が遅れても拾う猶予（Scheduler の間隔より長めに取る）
const SLOT_WINDOW_MS = 45 * 60 * 1000;

// 定期実行エンドポイント（Cloud Scheduler から5〜10分おきに叩く想定）。
//   task=publish  … 予約ストーリーズの公開
//   task=auto     … オートパイロット（自動生成→即投稿）
//   task=maintain … 長期トークンの自動リフレッシュ（1日1回程度で十分）
//   task=all      … 全部（デフォルト）
// CRON_SECRET を Authorization: Bearer（または ?secret=）で要求（設定時のみ）。
export async function GET(req: NextRequest) {
  const secret = process.env.CRON_SECRET;
  if (secret) {
    const provided =
      req.nextUrl.searchParams.get("secret") ||
      req.headers.get("authorization")?.replace(/^Bearer\s+/i, "") ||
      "";
    if (provided !== secret) {
      return Response.json({ error: "unauthorized" }, { status: 401 });
    }
  }

  const task = req.nextUrl.searchParams.get("task") ?? "all";
  const now = new Date();
  const summary = {
    task,
    published: 0,
    failed: 0,
    autoGenerated: 0,
    recurringRun: 0,
    recurringSkipped: 0,
    tokensRefreshed: 0,
    toneLearned: 0,
  };

  // ── 1) 予約ストーリーズの公開 ──
  if (task === "publish" || task === "all") {
    const due = await prisma.story.findMany({
      where: { status: "scheduled", scheduledAt: { lte: now } },
      select: { id: true },
      take: 20,
    });
    for (const { id } of due) {
      // 複数ランの二重投稿を防ぐため原子的に claim
      const claim = await prisma.story.updateMany({
        where: { id, status: "scheduled" },
        data: { status: "posting" },
      });
      if (claim.count === 0) continue;

      const r = await publishStoryRecord(id);
      if (r.ok) summary.published++;
      else summary.failed++;
    }
  }

  // ── 2) オートパイロット: 設定時刻が来たら自動生成→即投稿 ──
  if (task === "auto" || task === "all") {
    const accounts = await prisma.igAccount.findMany({
      where: { autoStoryEnabled: true, status: "connected", autoStoryTimes: { not: null } },
    });

    for (const account of accounts) {
      const slot = latestDueSlot(account.autoStoryTimes ?? "", now);
      if (!slot) continue;
      if (account.lastAutoStoryAt && account.lastAutoStoryAt.getTime() >= slot.getTime()) continue;

      // 先に lastAutoStoryAt を更新して同一スロットの二重生成を防ぐ
      const claim = await prisma.igAccount.updateMany({
        where: {
          id: account.id,
          OR: [{ lastAutoStoryAt: null }, { lastAutoStoryAt: { lt: slot } }],
        },
        data: { lastAutoStoryAt: now },
      });
      if (claim.count === 0) continue;

      try {
        const story = await autopilotCreateStory(account);
        await prisma.story.update({ where: { id: story.id }, data: { status: "posting" } });
        summary.autoGenerated++;

        const r = await publishStoryRecord(story.id);
        if (r.ok) summary.published++;
        else summary.failed++;
      } catch (e) {
        console.error(`autopilot failed for @${account.username}:`, e);
        summary.failed++;
      }
    }
  }

  // ── 2.5) 定期配信（「本日◯時オープン」等の繰り返し投稿） ──
  if (task === "recurring" || task === "all") {
    const due = await prisma.recurringStory.findMany({
      where: { enabled: true, nextRunAt: { lte: now } },
      take: 20,
    });
    for (const r of due) {
      // 窓を過ぎた分は投稿せず次回へ送る（「本日◯時」系の鮮度を守る）
      const skippedWindow = now.getTime() - r.nextRunAt.getTime() > RECURRING_WINDOW_MS;

      // 二重実行防止: nextRunAt を原子的に先送りして claim
      let next = new Date(r.nextRunAt.getTime() + r.intervalDays * 24 * 3600 * 1000);
      while (next.getTime() <= now.getTime()) {
        next = new Date(next.getTime() + r.intervalDays * 24 * 3600 * 1000);
      }
      const claim = await prisma.recurringStory.updateMany({
        where: { id: r.id, nextRunAt: r.nextRunAt },
        data: { nextRunAt: next, lastRunAt: now },
      });
      if (claim.count === 0) continue;

      const result = await runRecurring(r, { skippedWindow });
      if (result.ran) {
        summary.recurringRun++;
        if (result.published) summary.published++;
        else {
          summary.failed++;
          console.error(`recurring "${r.name}" failed:`, result.error);
        }
      } else {
        summary.recurringSkipped++;
      }
    }
  }

  // ── 3) 長期トークンの自動リフレッシュ（期限10日前から。getIgToken 内で判定） ──
  if (task === "maintain" || task === "all") {
    const soon = new Date(now.getTime() + 10 * 24 * 60 * 60 * 1000);
    const expiring = await prisma.igAccount.findMany({
      where: { status: "connected", tokenExpiresAt: { lte: soon } },
    });
    for (const account of expiring) {
      const token = await getIgToken(account);
      if (token) summary.tokensRefreshed++;
    }

    // 文体プロファイルの自動学習/更新（未学習 or 7日以上前。失敗時は toneProfileAt でバックオフ）
    const staleTone = await prisma.igAccount.findMany({
      where: {
        status: "connected",
        OR: [{ toneProfileAt: null }, { toneProfileAt: { lt: new Date(now.getTime() - TONE_REFRESH_MS) } }],
      },
      take: 5,
    });
    for (const account of staleTone) {
      try {
        await learnToneProfile(account);
        summary.toneLearned++;
      } catch (e) {
        console.log(`tone learn skipped for @${account.username}:`, e instanceof Error ? e.message : e);
        await prisma.igAccount.update({
          where: { id: account.id },
          data: { toneProfileAt: now },
        });
      }
    }
  }

  return Response.json({ ok: true, ...summary });
}

// オートパイロットの1枚を作成する。ソース設定（ai / library / mix）に従い、
// library はドライブ素材から（枯渇時はAI生成へフォールバック）、mix は交互。
async function autopilotCreateStory(account: IgAccount) {
  let useLibrary = false;
  if (account.autoStorySource === "library") {
    useLibrary = true;
  } else if (account.autoStorySource === "mix") {
    // 直近の自動投稿と逆のソースを使う（交互）
    const last = await prisma.story.findFirst({
      where: { igAccountId: account.id, source: "auto" },
      orderBy: { createdAt: "desc" },
      select: { sourceKind: true },
    });
    useLibrary = last?.sourceKind === "ai" || !last;
  }

  if (useLibrary) {
    const file = await pickLibraryFile(account);
    if (file) {
      return createStoryFromMedia(
        account,
        { kind: "library", fileId: file.id, mimeType: file.mimeType, fileName: file.name },
        { overlay: true, source: "auto" }
      );
    }
    // 素材がない場合はAI生成にフォールバック（自動運用を止めない）
    console.log(`autopilot: no library files for @${account.username}, falling back to AI`);
  }

  const recent = await prisma.story.findMany({
    where: { igAccountId: account.id, overlayTitle: { not: null } },
    orderBy: { createdAt: "desc" },
    take: 5,
    select: { overlayTitle: true },
  });
  const generated = await generateStory({
    username: account.username,
    theme: account.autoStoryTheme,
    recentTitles: recent.map((r) => r.overlayTitle!).filter(Boolean),
    style: account.autoStoryStyle,
    toneProfile: account.toneProfile,
  });
  return prisma.story.create({
    data: {
      organizationId: account.organizationId,
      igAccountId: account.id,
      concept: generated.concept,
      overlayTitle: generated.overlayTitle,
      overlaySub: generated.overlaySub,
      imagePrompt: generated.imagePrompt,
      imageData: generated.imageData,
      status: "draft",
      source: "auto",
    },
  });
}

// autoStoryTimes（JST "HH:mm,HH:mm"）から「現在時刻までに到来した最新スロット」を返す。
// 窓（SLOT_WINDOW_MS）を過ぎた古いスロットは対象外（サーバー停止中の分を後からまとめて投稿しない）。
function latestDueSlot(times: string, now: Date): Date | null {
  const jstNow = new Date(now.getTime() + 9 * 3600 * 1000);
  const y = jstNow.getUTCFullYear();
  const m = jstNow.getUTCMonth();
  const d = jstNow.getUTCDate();

  let latest: Date | null = null;
  for (const t of times.split(",")) {
    const match = /^([01]?\d|2[0-3]):([0-5]\d)$/.exec(t.trim());
    if (!match) continue;
    const hh = Number(match[1]);
    const mm = Number(match[2]);
    // 今日(JST)のスロットと前日(JST)のスロットの両方を判定（深夜0時またぎ対策）
    for (const dayOffset of [0, -1]) {
      const slot = new Date(Date.UTC(y, m, d + dayOffset, hh - 9, mm));
      const age = now.getTime() - slot.getTime();
      if (age >= 0 && age <= SLOT_WINDOW_MS) {
        if (!latest || slot.getTime() > latest.getTime()) latest = slot;
      }
    }
  }
  return latest;
}
